baseURL: https://squalr.us/
title: Chad Schulz
theme: hugo-notepadium
copyright: "©2021 Chad Schulz"

languageCode: en-us
enableRobotsTXT: true

googleAnalytics: UA-10469485-9

permalinks:
  blog: /:year/:month/:title/

params:
  style: "auto"
  dateFormat: "Monday, January 2, 2006"
  slogan: ""

  # homeSubtitle: info and stuff
  footerCopyright: Chad Schulz

  nav:
    showCategories: false
    showTags: false
    custom:
    - title: "GitHub"
      url: "https://github.com/squalrus"
    - title: "Twitter"
      url: "https://twitter.com/chadschulz"
    - title: "LinkedIn"
      url: "https://www.linkedin.com/in/chadschulz/"
