name: Merge Bot

on:
  pull_request_review:
    types: [submitted, dismissed]
  pull_request:
    types: [labeled, unlabeled]

jobs:
  merge:
    runs-on: ubuntu-latest
    name: Merge
    steps:
    - name: Integration check
      uses: squalrus/merge-bot@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        reviewers: false
        labels: ready
        method: 'squash'
